--  ANB Car Boosting 3.0
--  Edited: 7/3/23
--  By: Juugin

--Vechile Class S - Local Hyper cars and 3 High-Tier Import Cars [4 Cops needed online to boost]
    --Import Vehicles
    { name = "Nissan GT R34 Hycade", model = "hycader34", class = "S" },
    { name = "Ford GT", model = "gt17", class = "S" },
    { name = "Lexus LFA", model = "rmodlfa", class = "S" },

    --GTAV Vehicles
    { name = "Annis Elegy Retro", model = "elegy", class = "S" },
    { name = "Bravado Banshee 900R", model = "banshee2", class = "S" },
    { name = "Sultan RS", model = "sultanrs", class = "S" },
    { name = "Grotti Cheetah Classic", model = "cheetah2", class = "S" },
    { name = "Pegassi Infernus Classic", model = "infernus2", class = "S" },
    { name = "Progen Itali GTB Custom", model = "italigtb2", class = "S" },
    { name = "Grotti Furia", model = "furia", class = "S" },
    { name = "Coquette D10", model = "coquette4", class = "S" },
    { name = "Benefactor Krieger", model = "krieger", class = "S" },
    { name = "Bravado Gauntlet Hellfire", model = "gauntlet4", class = "S" },
    { name = "Grotti Itali RSX", model = "italirsx", class = "S" },
    { name = "Vapid FMJ", model = "fmj", class = "S" },
    { name = "Annis Elegy RH8", model = "elegy2", class = "S" },
    { name = "Ocelot Jugular", model = "jugular", class = "S" },
    { name = "Bravado Buffalo STX", model = "buffalo4", class = "S" },
    { name = "Ubermacht Sentinel Classic Widebody", model = "sentinel4", class = "S" },
    { name = "Dinka Jester RR", model = "jester4", class = "S" },


--Vehicle Class A - Local High-Tier Sport cars and 5 Mid-Tier Import Cars [4 Cops needed online to boost]
    --Import Vehicles
    { name = "Cadillac CT5 Blackwing", model = "ct5vblackwing", class = "A" },
    { name = "Mitsubishi Lancer Evo 9 Voltex", model = "evo9", class = "A" },
    { name = "BMW X7", model = "bmwg07", class = "A" },
    { name = "Nissan GT R35 Liberty Walk", model = "lwgtr", class = "A" },
    { name = "Porsche GT3 RS", model = "pruf", class = "A" },

    -- GTAV Vehicles
    { name = "Bravado Banshee", model = "banshee", class = "A" },
    { name = "Invetero Coquette", model = "coquette", class = "A" },
    { name = "Obey 9F", model = "ninef", class = "A" },
    { name = "Obey 9F Cabrio", model = "ninef2", class = "A" },
    { name = "Obey 8F Drafter", model = "drafter", class = "A" },
    { name = "Grotti Carbonizzare", model = "carbonizzare", class = "A" },
    { name = "Pfister Comet Retro", model = "comet3", class = "A" },
    { name = "Pfister Comet SR", model = "comet5", class = "A" },
    { name = "Dinka Jester Retro", model = "jester3", class = "A" },
    { name = "Lampadati Furore GT", model = "furoregt", class = "A" },
    { name = "Dinka Jester", model = "jester", class = "A" },
    { name = "Ocelot Lynx", model = "lynx", class = "A" },
    { name = "Dewbauchee Massacro", model = "massacro", class = "A" },
    { name = "Ocelot Pariah", model = "pariah", class = "A" },
    { name = "Hijak Ruston", model = "ruston", class = "A" },
    { name = "Enus Paragon", model = "paragon", class = "A" },
    { name = "Coil Voltic", model = "voltic", class = "A" },
    { name = "Infernus", model = "infernus", class = "A" },
    { name = "Bullet", model = "bullet", class = "A" },
    { name = "Pegassi Toros", model = "toros", class = "A" },
    { name = "Lampadati Novak", model = "novak", class = "A" },
    

--Vehicle Class B - Local Sport Cars [3 Cops needed online to boost]
    { name = "Ubermacht Sentinel SG4", model = "sentinelsg4", class = "B" },
    { name = "Pfister Comet", model = "comet2", class = "B" },
    { name = "Dewbauchee Specter", model = "specter", class = "B" },
    { name = "Vapid Dominator GTX", model = "dominator3", class = "B" },
    { name = "Bravado Gauntlet", model = "gauntlet", class = "B" },
    { name = "BF Weevil", model = "weevil", class = "B" },
    { name = "Dinka Sugoi", model = "sugoi", class = "B" },
    { name = "Grotti Brioso R/A", model = "brioso", class = "B" },
    { name = "Declasse Yosemite", model = "yosemite", class = "B" },
    { name = "Declasse Vamos", model = "vamos", class = "B" },
    { name = "Ocelot F620", model = "f620", class = "B" },
    { name = "Ubermacht Zion", model = "zion", class = "B" },
    { name = "Ubermacht Zion Cabrio", model = "zion2", class = "B" },
    { name = "Benefactor Surano", model = "surano", class = "B" },
    { name = "Maibatsu Penumbra FF", model = "penumbra2", class = "B" },
    { name = "Dewbauchee Rapid GT", model = "rapidgt", class = "B" },
    { name = "Dewbauchee Rapid GT Cabrio", model = "rapidgt2", class = "B" },
    { name = "Albany Alpha", model = "alpha", class = "B" },
    { name = "Canis Kamacho", model = "kamacho", class = "B" },
    { name = "Vapid Caracara", model = "caracara2", class = "B" },
    { name = "Coil Brawler", model = "brawler", class = "B" },
    { name = "Vapid Guardian", model = "guardian", class = "B" },
    { name = "Vapid Flash GT", model = "flashgt", class = "B" },
    { name = "Lampadati Komoda", model = "komoda", class = "B" },
    { name = "Albany VSTR", model = "vstr", class = "B" },
    { name = "Karin Kuruma", model = "kuruma", class = "B" },
    { name = "Karin Sultan", model = "sultan", class = "B" },
    { name = "Ubermacht Revolter", model = "revolter", class = "B" },
    { name = "Ubermacht Schafter V12", model = "schafter3", class = "B" },
    { name = "Ubermacht Schafter V12 LWB", model = "schafter4", class = "B" },
    { name = "Ocelot Jackal", model = "jackal", class = "B" },
    { name = "Ubermacht Oracle", model = "oracle", class = "B" },
    { name = "Ubermacht Oracle XS", model = "oracle2", class = "B" },
    { name = "Coil Raiden", model = "raiden", class = "B" },
    { name = "Ubermacht Sentinel", model = "sentinel", class = "B" },
    { name = "Karin Sultan Classic", model = "sultan2", class = "B" },
    { name = "Ubermacht Sentinel Classic", model = "sentinel3", class = "B" },
    { name = "Dewbauchee Exemplar", model = "exemplar", class = "B" },
    { name = "Pfister Neon", model = "neon", class = "B" },
    { name = "Declasse Vigero", model = "vigero", class = "B" },
    { name = "Lampadati Viseris", model = "viseris", class = "B" },
    { name = "Obey Omnis", model = "omnis", class = "B" },
    { name = "Vapid GB200", model = "gb200", class = "B" },
    { name = "Bravado Buffalo S", model = "buffalo2", class = "B" },
    { name = "Annis Hellion", model = "hellion", class = "B" },
    { name = "Vapid Desert Raid", model = "trophytruck2", class = "B" },
    { name = "Albany Hermes", model = "hermes", class = "B" },
    { name = "Nagaski Shinobi", model = "shinobi", class = "B" },
    { name = "Ubermacht Cypher", model = "cypher", class = "B" },
    { name = "Ubermacht Rebla GTS", model = "rebla", class = "B" },
    { name = "Annis Euros", model = "euros", class = "B" },
    { name = "Obey Emnis e-GT", model = "omnisegt", class = "B" },


--Vehicle Class C - Local sedans/coupes/SUVs/classics [2 Cops needed online to boost]
    { name = "Benefactor Feltzer", model = "feltzer2", class = "C" },
    { name = "Dewbauchee Specter Custom", model = "specter2", class = "C" },
    { name = "Karin 190z", model = "z190", class = "C" },
    { name = "Vapid Ellie", model = "ellie", class = "C" },
    { name = "Benefactor Schwartzer", model = "schwarzer", class = "C" },
    { name = "Declasse Tampa", model = "tampa", class = "C" },
    { name = "Imponte Ruiner", model = "ruiner", class = "C" },
    { name = "Imponte Dukes", model = "dukes", class = "C" },
    { name = "Vapid Dominator", model = "dominator", class = "C" },
    { name = "Enus Windsor", model = "windsor", class = "C" },
    { name = "Lampadati Felon GT", model = "felon2", class = "C" },
    { name = "Dinka Kanjo", model = "kanjo", class = "C" },
    { name = "Vapid Contender", model = "contender", class = "C" },
    { name = "Gallivanter Baller", model = "baller", class = "C" },
    { name = "Benefactor Dubsta 6x6", model = "dubsta3", class = "C" },
    { name = "Weeny Issi Sport", model = "issi7", class = "C" },
    { name = "Enus Windsor Drop", model = "windsor2", class = "C" },
    { name = "Ubermacht Schafter", model = "schafter2", class = "C" },
    { name = "Zirconium Stratum", model = "stratum", class = "C" },
    { name = "Enus Super Diamond", model = "superd", class = "C" },
    { name = "Lampadati Felon", model = "felon", class = "C" },
    { name = "Ubermacht Sentinel XS", model = "sentinel2", class = "C" },
    { name = "Ubermacht Zion Classic", model = "zion3", class = "C" },
    { name = "Annis Savestra", model = "savestra", class = "C" },
    { name = "Grotti Stinger", model = "stinger", class = "C" },
    { name = "Grotti Stinger GT", model = "stingergt", class = "C" },
    { name = "Benefactor Stirling GT", model = "feltzer3", class = "C" },
    { name = "Ocelot Swinger", model = "swinger", class = "C" },
    { name = "Invetero Coquette Classic", model = "coquette2", class = "C" },
    { name = "Invetero Coquette Blackfin", model = "coquette3", class = "C" },
    { name = "Bravado Buffalo", model = "buffalo", class = "C" },
    { name = "Declasse Mamba", model = "mamba", class = "C" },
    { name = "Vapid Trophy Truck", model = "trophytruck", class = "C" },
    { name = "Gallivanter Baller LE", model = "baller3", class = "C" },
    { name = "Declasse Sabre Turbo", model = "sabregt", class = "C" },
    { name = "Vapid Blade", model = "blade", class = "C" },
    { name = "Enus Cognoscenti Cabrio", model = "cogcabrio", class = "C" },
    { name = "Maibatsu Penumbra", model = "penumbra", class = "C" },
    { name = "Schyster Deviant", model = "deviant", class = "C" },
    { name = "Beater Dukes", model = "dukes3", class = "C" },
    { name = "Truffade Z-Type", model = "ztype", class = "C" },
    { name = "Vapid Chino Custom", model = "chino2", class = "C" },
    { name = "BF Injection", model = "bfinjection", class = "C" },
    { name = "Pfister Comet Safari", model = "comet4", class = "C" },
    { name = "Declasse Moonbeam Custom", model = "moonbeam2", class = "C" },
    { name = "Maxwell Vagrant", model = "vagrant", class = "C" },
    { name = "Karin Everon", model = "everon", class = "C" },
    { name = "Declasse Sabre Turbo Custom", model = "sabregt2", class = "C" },
    { name = "Declasse Tulip", model = "tulip", class = "C" },
    { name = "Vapid Retinue MkII", model = "retinue2", class = "C" },
    { name = "Lampadati Tropos Rallye", model = "tropos", class = "C" },
    { name = "Grotti GT500", model = "gt500", class = "C" },
    { name = "Lampadati Casco", model = "casco", class = "C" },
    { name = "Dewbauchee Rapid GT Classic", model = "rapidgt3", class = "C" },
    { name = "Shyster Fusilade", model = "fusilade", class = "C" },
    { name = "Karin Futo", model = "futo", class = "C" },
    { name = "Cheburek", model = "cheburek", class = "C" },
    { name = "Karin Intruder", model = "intruder", class = "C" },
    { name = "Dinka Blista", model = "blista", class = "C" },
    { name = "Lampadati Pigalle", model = "pigalle", class = "C" },
    { name = "Akuma", model = "AKUMA", class = "C" },
    { name = "Obey Tailgater", model = "tailgater", class = "C" },
    { name = "Willard Faction Custom", model = "faction2", class = "C" },
    { name = "Vapid Hotknife ", model = "hotknife", class = "C" },
    { name = "Benefactor XLS", model = "xls", class = "C" },
    { name = "Vapid Riata", model = "riata", class = "C" },


--Vehicle Class D - Local motorcycles/trucks/compact cars [Cops not needed online to boost]
    { name = "Enus Stafford", model = "stafford", class = "D" },
    { name = "Dinka Blista Compact", model = "blista2", class = "D" },
    { name = "Weeny Issi", model = "issi2", class = "D" },
    { name = "Benefactor Panto", model = "panto", class = "D" },
    { name = "Declasse Rhapsody", model = "rhapsody", class = "D" },
    { name = "Weeny Issi Classic", model = "issi3", class = "D" },
    { name = "Glendale Custom", model = "glendale2", class = "D" },
    { name = "Vulcar Warrener", model = "warrener", class = "D" },
    { name = "Vapid Chino", model = "chino", class = "D" },
    { name = "Willard Faction Donk", model = "faction3", class = "D" },
    { name = "Nagasaki Street Blazer", model = "blazer4", class = "D" },
    { name = "BF Bifta", model = "bifta", class = "D" },
    { name = "Karin BeeJay XL", model = "bjxl", class = "D" },
    { name = "Albany Cavalcade", model = "cavalcade", class = "D" },
    { name = "Fathom FQ-2", model = "fq2", class = "D" },
    { name = "Mammoth Patriot", model = "patriot", class = "D" },
    { name = "Benefactor Streiter", model = "streiter", class = "D" },
    { name = "Canis Mesa", model = "mesa", class = "D" },
    { name = "Bravado Rumpo Custom", model = "rumpo3", class = "D" },
    { name = "Declasse Moonbeam", model = "moonbeam", class = "D" },
    { name = "Bravado Gresley", model = "gresley", class = "D" },
    { name = "Enus Huntley S", model = "huntley", class = "D" },
    { name = "Obey Rocoto", model = "rocoto", class = "D" },
    { name = "Nagasaki Outlaw", model = "outlaw", class = "D" },
    { name = "Albany Virgo", model = "virgo", class = "D" },
    { name = "Albany Buccaneer Custom", model = "buccaneer2", class = "D" },
    { name = "Declasse Impaler", model = "impaler", class = "D" },
    { name = "Vapid Clique", model = "clique", class = "D" },
    { name = "Bravado Rat-Truck", model = "ratloader2", class = "D" },
    { name = "Lampadati Michelli GT", model = "michelli", class = "D" },
    { name = "Vapid Retinue", model = "retinue", class = "D" },
    { name = "Imponte Phoenix", model = "phoenix", class = "D" },
    { name = "Albany Buccaneer", model = "buccaneer", class = "D" },
    { name = "Declasse Stallion", model = "stalion", class = "D" },
    { name = "Cheval Surge", model = "surge", class = "D" },
    { name = "Cheval Fugitive", model = "fugitive", class = "D" },
    { name = "Declasse Premier", model = "premier", class = "D" },
    { name = "BF Club", model = "club", class = "D" },
    { name = "Bollokon Prairie", model = "prairie", class = "D" },
    { name = "Cheval Picador", model = "picador", class = "D" },
    { name = "Declasse Tornado Rat", model = "tornado6", class = "D" },
    { name = "Vulcar Nebula Turbo", model = "nebula", class = "D" },
    { name = "Imponte Nightshade", model = "nightshade", class = "D" },
    { name = "Albany Washington", model = "washington", class = "D" },
    { name = "Karin Asterope", model = "asterope", class = "D" },
    { name = "Vulcar Ingot", model = "ingot", class = "D" },
    { name = "Vapid Stanier", model = "stanier", class = "D" },
    { name = "Declasse Asea", model = "asea", class = "D" },
    { name = "Declasse Emperor", model = "emperor", class = "D" },
    { name = "Karin Dilettante", model = "dilettante", class = "D" },
    { name = "Vapid Hustler", model = "hustler", class = "D" },
    { name = "Albany Virgo Custom", model = "virgo2", class = "D" },
    { name = "Albany Virgo Classic", model = "virgo3", class = "D" },
    { name = "Weeny Dynasty", model = "dynasty", class = "D" },
    { name = "Manana Custom", model = "manana2", class = "D" },
    { name = "Declasse Tornado Custom", model = "tornado5", class = "D" },
    { name = "Brute Pony", model = "pony", class = "D" },
    { name = "Vapid Speedo", model = "speedo", class = "D" },
    { name = "Declasse Burrito", model = "burrito3", class = "D" },
    { name = "Bravado Youga Classic", model = "youga2", class = "D" },
    { name = "Vapid Minivan", model = "minivan", class = "D" },
    { name = "Declasse Burrito G", model = "gburrito", class = "D" },
    { name = "Nagasaki Blazer", model = "blazer", class = "D" },
    { name = "Ratbike", model = "ratbike", class = "D" },
    { name = "Bagger", model = "bagger", class = "D" },
    { name = "Bati 801", model = "bati", class = "D" },
    { name = "Bati 801RR", model = "bati2", class = "D" },
    { name = "BF400", model = "bf400", class = "D" },
    { name = "Carbon RS", model = "carbonrs", class = "D" },
    { name = "Cliffhanger", model = "cliffhanger", class = "D" },
    { name = "Daemon", model = "daemon", class = "D" },
    { name = "Double T", model = "double", class = "D" },
    { name = "Enduro", model = "enduro", class = "D" },
    { name = "Gargoyle", model = "gargoyle", class = "D" },
    { name = "Hakuchou", model = "hakuchou", class = "D" },
    { name = "Hexer", model = "hexer", class = "D" },
    { name = "Innovation", model = "innovation", class = "D" },
    { name = "Lectro", model = "lectro", class = "D" },
    { name = "Nemesis", model = "nemesis", class = "D" },
    { name = "PCJ-600", model = "pcj", class = "D" },
    { name = "Ruffian", model = "ruffian", class = "D" },
    { name = "Sanchez", model = "sanchez", class = "D" },
    { name = "Manchez", model = "manchez", class = "D" },
    { name = "Sovereign", model = "sovereign", class = "D" },
    { name = "Thrust", model = "thrust", class = "D" },
    { name = "Shotaro", model = "SHOTARO", class = "D" },
    { name = "Vindicator", model = "vindicator", class = "D" },
    { name = "Zombiea", model = "zombiea", class = "D" },
    { name = "Zombieb", model = "zombieb", class = "D" },
    { name = "Wolfsbane", model = "wolfsbane", class = "D" },
    { name = "Nightblade", model = "nightblade", class = "D" },
    { name = "Faggio Custom", model = "faggio3", class = "D" },
    { name = "Cliffhanger", model = "Cliffhanger", class = "D" },
    { name = "Daemon Custom", model = "daemon2", class = "D" },


--Unused Vehicles
--{ name = "Faggio", model = "faggio2", class = "D" },
--{ name = "Faggio", model = "faggio", class = "D" },
--{ name = "Asbo", model = "asbo", class = "C" },
--{ name = "Declasse Emperor (Rusty)", model = "emperor2", class = "D" },
--{ name = "Dundreary Regina", model = "regina", class = "D" },
--{ name = "Enus Cognoscenti", model = "cognoscenti", class = "B" },
--{ name = "Enus Cognoscenti 55", model = "cog55", class = "B" },
--{ name = "Albany Primo", model = "primo", class = "C" },
--{ name = "Albany Primo Custom", model = "primo2", class = "C" },
--{ name = "Vapid Taxi", model = "taxi", class = "C" },
--{ name = "Dundreary Stretch", model = "stretch", class = "C" },
--{ name = "Vulcar Fagaloa", model = "fagaloa", class = "C" },
--{ name = "Declasse Tornado", model = "tornado", class = "D" },
--{ name = "Declasse Tornado Cabrio", model = "tornado2", class = "D" },
--{ name = "Declasse Voodoo", model = "voodoo2", class = "D" },
--{ name = "Declasse Voodoo Custom", model = "voodoo", class = "D" },
--{ name = "Declasse Tornado (Rusty)", model = "tornado3", class = "D" },
--{ name = "Vapid Peyote", model = "peyote", class = "D" },
--{ name = "Chariot Romero Hearse", model = "romero", class = "D" },
--{ name = "Vapid Slamvan", model = "slamvan", class = "A" },
--{ name = "Vapid Slamvan Custom", model = "slamvan3", class = "A" },
--{ name = "Willard Faction", model = "faction", class = "B" },
--{ name = "Bravado Rat-Loader", model = "ratloader", class = "C" },
--{ name = "Benefactor Glendale", model = "glendale", class = "C" },
--{ name = "Declasse Hotring Sabre", model = "hotring", class = "S" },
--{ name = "Canis Freecrawler", model = "freecrawler", class = "C" },
--{ name = "Canis Bodhi", model = "bodhi2", class = "D" },
--{ name = "Declasse Rancher XL", model = "rancherxl", class = "D" },
--{ name = "Bravado Duneloader", model = "dloader", class = "D" },
--{ name = "Vapid Sadler", model = "sadler", class = "D" },
--{ name = "Vapid Sandking XL", model = "sandking", class = "D" },
--{ name = "Vapid Sandking", model = "sandking2", class = "D" },
--{ name = "Canis Kalahari", model = "kalahari", class = "D" },
--{ name = "Benefactor Dubsta Mandem", model = "dubsta2", class = "B" },
--{ name = "Benefactor Dubsta", model = "dubsta", class = "B" },
--{ name = "Benefactor Serrano", model = "serrano", class = "B" },
--{ name = "Landstalker XL", model = "landstalker2", class = "C" },
--{ name = "Gallivanter Baller", model = "baller2", class = "C" },
--{ name = "Albany Cavalcade", model = "cavalcade2", class = "C" },
--{ name = "Declasse Granger", model = "granger", class = "C" },
--{ name = "Emperor Habanero", model = "habanero", class = "C" },
--{ name = "Dundreary Landstalker", model = "landstalker", class = "C" },
--{ name = "Mammoth Patriot WCR", model = "patriot2", class = "C" },
--{ name = "Vapid Radius", model = "radi", class = "C" },
--{ name = "Canis Seminole", model = "seminole", class = "C" },
--{ name = "Vapid Bobcat XL", model = "bobcatxl", class = "C" },
--{ name = "Karin Rebel", model = "rebel", class = "C" },
--{ name = "Karin Rebel", model = "rebel2", class = "C" },
--{ name = "Canis Kamacho", model = "kamacho", class = "C" },
--{ name = "Canis Mesa", model = "mesa", class = "C" },
--{ name = "Bravado Paradise", model = "paradise", class = "D" },
--{ name = "Flatbed", model = "flatbed", class = "C" },
--{ name = "Manana", model = "manana", class = "D" },
--{ name = "Bravado Rumpo News", model = "rumpo", class = "D" },
--{ name = "Zirconium Journey", model = "journey", class = "D" },
--{ name = "BF Surfer", model = "surfer", class = "D" },
--{ name = "BF Surfer Kona", model = "surfer2", class = "D" },
--{ name = "Brute Camper", model = "camper", class = "D" },
--{ name = "Minivan Custom", model = "minivan2", class = "B" },
--{ name = "Bravado Youga", model = "youga", class = "C" },
--{ name = "BMX", model = "bmx", class = "C" },
--{ name = "Cruiser", model = "cruiser", class = "C" },
--{ name = "Fixter", model = "fixter", class = "C" },
--{ name = "Scorcher", model = "scorcher", class = "C" },
--{ name = "Pro 1", model = "tribike", class = "C" },
--{ name = "Pro 2", model = "tribike2", class = "C" },
--{ name = "Pro 3", model = "tribike3", class = "C" },
--{ name = "Mammoth Squaddie", model = "squaddie", class = "B" },
--{ name = "Maibatsu Manchez Scout", model = "manchez2", class = "B" },
--{ name = "Brioso Classic", model = "brioso2", class = "C" },
--{ name = "Vapid Winky", model = "winky", class = "C" },
